"""Create new modle Categories

Revision ID: 2d6b7cae2718
Revises: e1ce9a2e6f08
Create Date: 2024-12-20 11:47:51.326047

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2d6b7cae2718'
down_revision = 'e1ce9a2e6f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id_categories', sa.Uuid(), nullable=False))
    op.drop_column('categories', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'id_categories')
    # ### end Alembic commands ###
