"""Create new modle Categories

Revision ID: 9600f4b3ca67
Revises: 68fe7306d62b
Create Date: 2024-12-20 13:37:50.098920

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9600f4b3ca67'
down_revision = '68fe7306d62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id_categories', sa.Uuid(), nullable=False))
    op.drop_column('categories', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'id_categories')
    # ### end Alembic commands ###
