"""Create new modle Categories

Revision ID: 9ddcc15dc556
Revises: 2d6b7cae2718
Create Date: 2024-12-20 13:27:27.803377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ddcc15dc556'
down_revision = '2d6b7cae2718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id_categories', sa.Uuid(), nullable=False))
    op.drop_column('categories', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'id_categories')
    # ### end Alembic commands ###
