"""Create new modle Categories

Revision ID: e1ce9a2e6f08
Revises: a996fa4ded8f
Create Date: 2024-12-20 11:42:04.096133

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e1ce9a2e6f08'
down_revision = 'a996fa4ded8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id_categories', sa.Uuid(), nullable=False))
    op.drop_column('categories', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'id_categories')
    # ### end Alembic commands ###
