"""fix task version

Revision ID: e66c1cb3b6f8
Revises: ef8a25314876
Create Date: 2024-12-27 14:53:22.887551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e66c1cb3b6f8'
down_revision: Union[str, None] = 'ef8a25314876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'notes_id',
               existing_type=sa.UUID(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'notes_id',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
